//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorMon.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Metadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Metadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorMon.Resource.Metadata", typeof(Metadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرفته.
        /// </summary>
        public static string Enum_PostLevel_Advance {
            get {
                return ResourceManager.GetString("Enum_PostLevel_Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدماتی.
        /// </summary>
        public static string Enum_PostLevel_Intro {
            get {
                return ResourceManager.GetString("Enum_PostLevel_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        public static string Enum_PostLevel_Typical {
            get {
                return ResourceManager.GetString("Enum_PostLevel_Typical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نویس.
        /// </summary>
        public static string Enum_PublishStatus_Draft {
            get {
                return ResourceManager.GetString("Enum_PublishStatus_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتشر.
        /// </summary>
        public static string Enum_PublishStatus_Publish {
            get {
                return ResourceManager.GetString("Enum_PublishStatus_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایندکس محتوا و دنبال کردن لینک ها.
        /// </summary>
        public static string Enum_RobotsState_Global {
            get {
                return ResourceManager.GetString("Enum_RobotsState_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط ایندکس کردن محتوا.
        /// </summary>
        public static string Enum_RobotsState_NoFollow {
            get {
                return ResourceManager.GetString("Enum_RobotsState_NoFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم ایندکس و دنبال کردن لینک ها.
        /// </summary>
        public static string Enum_RobotsState_NoFollowNoIndex {
            get {
                return ResourceManager.GetString("Enum_RobotsState_NoFollowNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط دنبال کردن لینک ها.
        /// </summary>
        public static string Enum_RobotsState_NoIndex {
            get {
                return ResourceManager.GetString("Enum_RobotsState_NoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صعودی.
        /// </summary>
        public static string Enum_SortOrder_Asc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نزولی.
        /// </summary>
        public static string Enum_SortOrder_Desc {
            get {
                return ResourceManager.GetString("Enum_SortOrder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسنده.
        /// </summary>
        public static string Post_Author {
            get {
                return ResourceManager.GetString("Post_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوی.
        /// </summary>
        public static string Post_Content {
            get {
                return ResourceManager.GetString("Post_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای مطلب را وارد کنید.
        /// </summary>
        public static string Post_Content_Required {
            get {
                return ResourceManager.GetString("Post_Content_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string Post_CreateDateTime {
            get {
                return ResourceManager.GetString("Post_CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توصیف.
        /// </summary>
        public static string Post_MetaDescription {
            get {
                return ResourceManager.GetString("Post_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیدواژه ها.
        /// </summary>
        public static string Post_MetaKeyWords {
            get {
                return ResourceManager.GetString("Post_MetaKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش.
        /// </summary>
        public static string Post_ModifiedDateTime {
            get {
                return ResourceManager.GetString("Post_ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح مطلب.
        /// </summary>
        public static string Post_PostLevel {
            get {
                return ResourceManager.GetString("Post_PostLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح مطلب را مشخص کنید.
        /// </summary>
        public static string Post_PostLevel_Required {
            get {
                return ResourceManager.GetString("Post_PostLevel_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتشار.
        /// </summary>
        public static string Post_PublishDateTime {
            get {
                return ResourceManager.GetString("Post_PublishDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتشار را وارد کنید.
        /// </summary>
        public static string Post_PublishDateTime_Required {
            get {
                return ResourceManager.GetString("Post_PublishDateTime_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت انتشار.
        /// </summary>
        public static string Post_PublishStatus {
            get {
                return ResourceManager.GetString("Post_PublishStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت انتشار را مشخص کنید.
        /// </summary>
        public static string Post_PublishStatus_Required {
            get {
                return ResourceManager.GetString("Post_PublishStatus_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت موتورهای جستجو.
        /// </summary>
        public static string Post_RobotsState {
            get {
                return ResourceManager.GetString("Post_RobotsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت موتورهای جستجو را مشخص کنید.
        /// </summary>
        public static string Post_RobotsState_Required {
            get {
                return ResourceManager.GetString("Post_RobotsState_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Post_Title {
            get {
                return ResourceManager.GetString("Post_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مطلب را وارد کنید.
        /// </summary>
        public static string Post_Title_Required {
            get {
                return ResourceManager.GetString("Post_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامک.
        /// </summary>
        public static string Post_UrlTitle {
            get {
                return ResourceManager.GetString("Post_UrlTitle", resourceCulture);
            }
        }
    }
}
